categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '📝 Documentation'
    label: 'documentation'
  - title: '🤖 DevOps'
    labels:
      - 'DevOps'
      - 'devops'
      - 'CI'
  - title: '🔬 Research'
    label: 'research'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES
