name: Internal continuous delivery & deployment

on:
  push:
    branches:
      - develop
      - main

jobs:

  push-latest-build:

    name: Build docker image and publish to ECR
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Extraction of image build timestamp
      uses: josStorer/get-current-time@v2
      id: latest-image-build
      with:
        format: YYYY-MM-DD--HH-mm-ss
        utcOffset: "+00:00"

    - name: Print timestamp based build image tag
      env:
        image_tag: ${{ steps.latest-image-build.outputs.formattedTime }}
      run: echo $image_tag

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ steps.latest-image-build.outputs.formattedTime }}
      run: |
        docker build -f docker/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --no-cache --force-rm .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    outputs:
      build-tag: ${{ steps.latest-image-build.outputs.formattedTime }}

  infrastucture-deployment:

    runs-on: ubuntu-latest
    needs: push-latest-build
    strategy:
      matrix:
        environment: [dev, test]

    steps:

    - uses: actions/checkout@v2

    - name: "Setup AWS Credentials"
      run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.8

    - name: Glue tables | Init
      id: glue-table-init
      env:
        TF_WORKSPACE: ${{ matrix.environment }}
      run: cd terraform/glue/tables && make init

    - name: Glue tables | Validate
      id: glue-table-validate
      run: cd terraform/glue/tables && terraform validate -no-color

    - name: Glue tables | Plan
      id: glue-table-plan
      env:
        TF_WORKSPACE: ${{ matrix.environment }}
      run: cd terraform/glue/tables && make plan
      continue-on-error: false

    - name: Glue tables | Status Check
      id: glue-table-status-check
      if: steps.glue-table-plan.outcome == 'failure'
      run: exit 1

    - name: Glue tables | Apply
      if: ${{ !(contains(github.ref_name, 'develop') && (matrix.environment == 'test')) }}
      id: glue-table-apply
      env:
        TF_WORKSPACE: ${{ matrix.environment }}
      run: cd terraform/glue/tables && make apply

    - name: Lambda | Init
      id: lambda-init
      env:
        TF_WORKSPACE: ${{ matrix.environment }}
      run: cd terraform/lambda && make init

    - name: Lambda | Validate
      id: lambda-validate
      run: cd terraform/lambda && terraform validate -no-color

    - name: Lambda | Plan
      id: lambda-plan
      env:
        TF_WORKSPACE: ${{ matrix.environment }}
      run: cd terraform/lambda && make plan
      continue-on-error: false

    - name: Lambda | Status Check
      id: lambda-status-check
      if: steps.lambda-plan.outcome == 'failure'
      run: exit 1

    - name: Lambda | Apply
      if: ${{ !(contains(github.ref_name, 'develop') && (matrix.environment == 'test')) }}
      id: lambda-apply
      env:
        TF_WORKSPACE: ${{ matrix.environment }}
      run: cd terraform/lambda && make apply
